//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace UnityUtilLib {
	public interface IPool {
		object Get();
		void Return (object obj);
	}

	public interface IPool<T> : IPool where T : IPooledObject {
		new T Get();
		void Return(T obj);
	}
}